<?php
$objJTage = '{
                "tage":
                [       
                    {
                        "tag":"01",
                        "thema":"",
                        "dateien":[
                            {
                            "datei":"1_T01Einfuehrung.php",
                            "titel":"101Einfuehrung",
                            "beschreibung":""
                            }
                        ]
                    },
                    {
                        "tag":"02",
                        "thema":"",
                        "dateien":[
                            {
                                "datei":"1_T02Selectoren.php",
                                "titel":"102Selectoren",
                                "beschreibung":""
                            }
                         ]
                    },
                    {
                        "tag":"03",
                        "thema":"Vereinfachungen",
                        "dateien":[
                            {
                                "datei":"1_T03Vereinfachungen.php",
                                "titel":"103Vereinfachungen",
                                "beschreibung":""
                            }
                        ]
                     },
                    {
                        "tag":"04",
                        "thema":"Filter",
                        "dateien":[
                            {
                                "datei":"1_T04Filter.php",
                                "titel":"104Filter",
                                "beschreibung":""
                            },
                            {
                                "datei":"1_T04Traverse_Filter.php",
                                "titel":"104Traverse_Filter",
                                "beschreibung":""
                            },
                            {
                                "datei":"2_T04Filter.php",
                                "titel":"204Filter",
                                "beschreibung":""
                            },
                            {
                                "datei":"2_T04Traverse.php",
                                "titel":"204Traverse",
                                "beschreibung":""
                            },
                            {
                                "datei":"3_T04Traverse.php",
                                "titel":"304Traverse",
                                "beschreibung":""
                            },
                            {
                                "datei":"4_T04Animation.php",
                                "titel":"404Animation",
                                "beschreibung":""
                            }
                        ]
                     },
                    {
                        "tag":"05",
                        "thema":"Animation, Accessor, Events",
                        "dateien":[
                            {
                                "datei":"1_T05Animation.php",
                                "titel":"105Animation",
                                "beschreibung":""
                            },
                            {
                                "datei":"2_T05Accessor.php",
                                "titel":"205Accessor",
                                "beschreibung":""
                            },
                            {
                                "datei":"3_T05Events.php",
                                "titel":"305Events",
                                "beschreibung":""
                            }
                        ]
                    },
                    {
                        "tag":"06",
                        "thema":"Eventhandling, Formulare, Inhalte",
                        "dateien":[
                            {
                                "datei":"1_T06Event.php",
                                "titel":"106Event",
                                "beschreibung":""
                            },
                            {
                                "datei":"1_T06Formulare.php",
                                "titel":"106Formulare",
                                "beschreibung":""
                            },
                            {
                                "datei":"2_T06Event.php",
                                "titel":"206Event",
                                "beschreibung":""
                            },
                            {
                                "datei":"3_T06Inhalte.php",
                                "titel":"306Inhalte",
                                "beschreibung":""
                            },
                            {
                                "datei":"4_T06Inhalte.php",
                                "titel":"406Inhalte",
                                "beschreibung":""
                            },
                            {
                                "datei":"5_T06Inhalte.php",
                                "titel":"506Inhalte",
                                "beschreibung":""
                            }
                        ]
                    },
                    {
                        "tag":"07",
                        "thema":"Formulare",
                        "dateien":[
                            {
                            "datei":"1_T07formulare.php",
                            "titel":"107formulare",
                            "beschreibung":""
                            },
                            {
                            "datei":"2_T07formulare.php",
                            "titel":"207formulare",
                            "beschreibung":""
                            }
                        ]
                    },
                    {
                        "tag":"08",
                        "thema":"Animation, Data",
                        "dateien":[
                            {
                                "datei":"1_T08Animation.php",
                                "titel":"108Animation",
                                "beschreibung":""
                            },
                            {
                                "datei":"1_T08Data.php",
                                "titel":"108Data",
                                "beschreibung":""
                            },
                            {
                                "datei":"1_T08blubb.php",
                                "titel":"108blubb",
                                "beschreibung":""
                            },
                            {
                                "datei":"2_T08data.php",
                                "titel":"208data",
                                "beschreibung":""
                            }
                        ]
                    },
                    {
                        "tag":"09",
                        "thema":"",
                        "dateien":[
                            {
                                "datei":"1_T09Animation.php",
                                "titel":"109Animation",
                                "beschreibung":""
                            }
                        ]
                    },
                    {
                        "tag":"10",
                        "thema":"",
                        "dateien":[
                            {
                                "datei":"1_T10Animation.php",
                                "titel":"110Animation",
                                "beschreibung":""
                            },
                            {
                                "datei":"1_T10PluginGalerie.php",
                                "titel":"110PluginGalerie",
                                "beschreibung":""
                            },
                            {
                                "datei":"1_T10Zebra.php",
                                "titel":"110Zebra",
                                "beschreibung":""
                            },
                            {
                                "datei":"2_T10Animation.php",
                                "titel":"210Animation",
                                "beschreibung":""
                            },
                            {
                                "datei":"4_T10Animation.php",
                                "titel":"410Animation",
                                "beschreibung":""
                            }
                        ]
                    },
                    {
                        "tag":"12",
                        "thema":"",
                        "dateien":[
                            {
                                "datei":"1_T12ajax.php",
                                "titel":"112ajax",
                                "beschreibung":""
                            },
                            {
                                "datei":"2_T12ajax.php",
                                "titel":"212ajax",
                                "beschreibung":""
                            },
                            {
                                "datei":"3_T12ajax.php",
                                "titel":"312ajax",
                                "beschreibung":""
                            }
                        ]
                    },
                    {
                        "tag":"13",
                        "thema":"",
                        "dateien":[
                            {
                                "datei":"1_T13plugin4.php",
                                "titel":"113plugin4",
                                "beschreibung":""
                            }
                        ]
                    },
                    {
                        "tag":"14",
                        "thema":"",
                        "dateien":[
                            {
                                "datei":"1_T14plugin.php",
                                "titel":"114plugin",
                                "beschreibung":""

                            }
                    ]
                    },
                    {
                        "tag":"15",
                        "thema":"",
                        "dateien":[
                            {
                                "datei":"1_T15Ajax.php",
                                "titel":"115Ajax",
                                "beschreibung":""
                            },
                            {
                                "datei":"3_T15ajax.php",
                                "titel":"315ajax",
                                "beschreibung":""
                            },
                            {
                                "datei":"4_T15ajax.php",
                                "titel":"415ajax",
                                "beschreibung":""
                            }
                        ]
                    },
                    {
                        "tag":"16",
                        "thema":"",
                        "dateien":[
                            {
                                "datei":"1_T16AjaxPlugin.php",
                                "titel":"116AjaxPlugin",
                                "beschreibung":""
                            },
                            {
                                "datei":"2_T16AjaxPlugin.php",
                                "titel":"216AjaxPlugin",
                                "beschreibung":""
                            },
                            {
                                "datei":"2_T16Links.php",
                                "titel":"216Links",
                                "beschreibung":""
                            }
                        ]
                    },
                    {
                        "tag":"17",
                        "thema":"",
                        "dateien":[
                            {
                                "datei":"1_T17json.php",
                                "titel":"117json",
                                "beschreibung":""
                            },
                            {
                                "datei":"2_T17AjaxNavigation.php",
                                "titel":"217AjaxNavigation",
                                "beschreibung":""
                            }
                        ]
                    },
                    {
                        "tag":"18",
                        "thema":"",
                        "dateien":[
                            {
                                "datei":"1_T18AjaxXML.php",
                                "titel":"118AjaxXML",
                                "beschreibung":""
                            }
                        ]
                    },
                    {
                        "tag":"19",
                        "thema":"",
                        "dateien":[
                            {
                                "datei":"1_T19TabelleGrid.php",
                                "titel":"119TabelleGrid",
                                "beschreibung":""
                            },
                            {
                                "datei":"1_T19Tabellesortieren.php",
                                "titel":"119Tabellesortieren",
                                "beschreibung":""
                            },
                            {
                                "datei":"2_T19AjaxDateinenLaden.php",
                                "titel":"219AjaxDateinenLaden",
                                "beschreibung":""
                            }
                        ]
                    },
                    {
                        "tag":"20",
                        "thema":"Übungen",
                        "dateien":[
                            {
                                "datei":"1_T20Uebungen.php",
                                "titel":"120Uebungen",
                                "beschreibung":""
                            }
                           ]
                     }
               ]
         }';
?>
